name = "ruby-driver"
title = "Ruby MongoDB Driver"
eol = true

intersphinx = ["https://www.mongodb.com/docs/manual/objects.inv"]

[[banners]]
targets = ["*"]
variant = "info"
value = """\
    This version of the documentation is archived and no longer supported. View the `current documentation <https://www.mongodb.com/docs/ruby-driver/current/>`__ to learn how to `upgrade your version of the Ruby MongoDB Driver <https://www.mongodb.com/docs/ruby-driver/current/installation/>`__.\
    """
